### PR TITLE
[ready] check for conflicting packages by name/version

### PR DESCRIPTION
**Pull request by sbma44**
fixes https://github.com/mapbox/npm-internal/issues/3

### CODE REVIEW

**Comment by yhahn** [comment]
@sbma44 want to get testing of this module kicked off by adding a test for this?

**Comment by sbma44** [comment]
@yhahn will do

**Comment by sbma44** [comment]
ooookay, added a test. I didn't wire up Travis yet: the tests depend on S3, and the only AWS creds I've got are MFA-dependent. Maybe tomorrow we can talk about how we drop permanent versions into Travis encrypted variables.

**Comment by yhahn** [comment]
:+1:

**Comment by sbma44** [comment]
@mick I'm told you possess the secret arcane knowledge by which Travis is given AWS credentials. I'll be in SF 2/1-2/6, maybe we can sync on this then & wire up these tests? Can't imagine it'll take long.

**Comment by mick** [comment]
@sbma44 sure thing. The other option that I been liking lately is `mock-aws-s3`. We use it in the [cardboard tests](https://github.com/mapbox/cardboard/blob/master/test/setup.js#L4). It makes sense for straightforward usages of S3 like this. 

Thanks for adding tests!

**Comment by sbma44** [comment]
OK, `mock-aws-s3` is in place. I don't have Github admin rights so I can't turn on Travis for this repo; can one of you guys do it & we'll confirm tests are passing?

**Comment by mick** [comment]
done. test are passing :balloon:  

Can we switch out async for [queue-async](https://www.npmjs.com/package/queue-async)?

**Comment by sbma44** [comment]
no real objection from me, but can I ask why? I saw Tom M also say that he didn't like `async` -- I'm still a Node baby, so I trust there's a reason I don't yet know. I default to `async` simply because I've often found myself working on projects with redundant async helper libraries, all of them offering a subset of `async` functionality. Seems simpler to just use the slightly-ugly one that can do everything.

**Comment by mick** [comment]
@sbma44 we've tried several flow control libs, and run into some traps with now async and step handles errors. Async can work, and you can handle the error cases, but its added features have introduced some added traps. After being burned we switched and in most mapbox code we've stuck with the simplicity of queue-async and/or named functions.

**Comment by sbma44** [comment]
got it. ready to merge if you think it looks OK.

**Pull request merged**
